import com.kennycason.kumo.CollisionMode;
import com.kennycason.kumo.Word;
import com.kennycason.kumo.WordCloud;
import com.kennycason.kumo.WordFrequency;
import com.kennycason.kumo.bg.PixelBoundryBackground;
import com.kennycason.kumo.font.scale.LinearFontScalar;
import com.kennycason.kumo.font.scale.SqrtFontScalar;
import com.kennycason.kumo.image.AngleGenerator;
import com.kennycason.kumo.palette.ColorPalette;

import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Abc {
    public static void main(String[] args) throws IOException {

        final List<WordFrequency> wordFrequencies = new ArrayList<WordFrequency>();
        wordFrequencies.add(new WordFrequency("London", 621));
        wordFrequencies.add(new WordFrequency("Sao Paulo", 491));
        wordFrequencies.add(new WordFrequency("Berlin", 382));
        wordFrequencies.add(new WordFrequency("Seattle", 376));
        wordFrequencies.add(new WordFrequency("Moscow", 344));
        wordFrequencies.add(new WordFrequency("New York", 264));
        wordFrequencies.add(new WordFrequency("Stockholm", 232));
        wordFrequencies.add(new WordFrequency("Paris", 229));
        wordFrequencies.add(new WordFrequency("Munich", 225));
        wordFrequencies.add(new WordFrequency("Minato City", 213));
        wordFrequencies.add(new WordFrequency("Warsaw", 212));
        wordFrequencies.add(new WordFrequency("San Francisco", 207));
        wordFrequencies.add(new WordFrequency("Bengaluru", 203));
        wordFrequencies.add(new WordFrequency("Saint Petersburg", 193));
        wordFrequencies.add(new WordFrequency("Barcelona", 190));
        wordFrequencies.add(new WordFrequency("Amsterdam", 181));
        wordFrequencies.add(new WordFrequency("Sydney", 178));
        wordFrequencies.add(new WordFrequency("Kyiv", 178));
        wordFrequencies.add(new WordFrequency("Oslo Municipality", 169));
        wordFrequencies.add(new WordFrequency("Hamburg", 168));
        wordFrequencies.add(new WordFrequency("Ashburn", 158));
        wordFrequencies.add(new WordFrequency("Jakarta", 153));
        wordFrequencies.add(new WordFrequency("Shibuya City", 153));
        wordFrequencies.add(new WordFrequency("Madrid", 152));
        wordFrequencies.add(new WordFrequency("Chiyoda City", 152));
        wordFrequencies.add(new WordFrequency("Minsk", 148));
        wordFrequencies.add(new WordFrequency("Seoul", 148));
        wordFrequencies.add(new WordFrequency("Wroclaw", 145));
        wordFrequencies.add(new WordFrequency("Chicago", 141));
        wordFrequencies.add(new WordFrequency("Tel Aviv-Yafo", 139));
        wordFrequencies.add(new WordFrequency("Melbourne", 137));
        wordFrequencies.add(new WordFrequency("Prague", 137));
        wordFrequencies.add(new WordFrequency("Frankfurt", 137));
        wordFrequencies.add(new WordFrequency("Rio de Janeiro", 132));
        wordFrequencies.add(new WordFrequency("Dublin", 127));
        wordFrequencies.add(new WordFrequency("Hyderabad", 122));
        wordFrequencies.add(new WordFrequency("Krakow", 119));
        wordFrequencies.add(new WordFrequency("Campinas", 116));
        wordFrequencies.add(new WordFrequency("Poznan", 109));
        wordFrequencies.add(new WordFrequency("Toronto", 108));
        wordFrequencies.add(new WordFrequency("Budapest", 106));
        wordFrequencies.add(new WordFrequency("Istanbul", 104));
        wordFrequencies.add(new WordFrequency("Kharkiv", 102));
        wordFrequencies.add(new WordFrequency("Denver", 102));
        wordFrequencies.add(new WordFrequency("Montreal", 95));
        wordFrequencies.add(new WordFrequency("Los Angeles", 95));
        wordFrequencies.add(new WordFrequency("San Jose", 95));
        wordFrequencies.add(new WordFrequency("Cologne", 91));
        wordFrequencies.add(new WordFrequency("Pune", 91));
        wordFrequencies.add(new WordFrequency("Bellevue", 91));
        wordFrequencies.add(new WordFrequency("Shinjuku City", 90));
        wordFrequencies.add(new WordFrequency("Belo Horizonte", 89));
        wordFrequencies.add(new WordFrequency("Zurich", 89));
        wordFrequencies.add(new WordFrequency("Mumbai", 87));
        wordFrequencies.add(new WordFrequency("Chennai", 87));
        wordFrequencies.add(new WordFrequency("Bangkok", 86));
        wordFrequencies.add(new WordFrequency("Boardman", 86));
        wordFrequencies.add(new WordFrequency("Vienna", 85));
        wordFrequencies.add(new WordFrequency("Helsinki", 82));
        wordFrequencies.add(new WordFrequency("Hong Kong", 81));
        wordFrequencies.add(new WordFrequency("Santa Monica", 78));
        wordFrequencies.add(new WordFrequency("Ho Chi Minh City", 77));
        wordFrequencies.add(new WordFrequency("Astana", 75));
        wordFrequencies.add(new WordFrequency("Buenos Aires", 74));
        wordFrequencies.add(new WordFrequency("Stuttgart", 71));
        wordFrequencies.add(new WordFrequency("Austin", 69));
        wordFrequencies.add(new WordFrequency("Karlsruhe", 67));
        wordFrequencies.add(new WordFrequency("Boston", 67));
        wordFrequencies.add(new WordFrequency("Chuo City", 67));
        wordFrequencies.add(new WordFrequency("Minneapolis", 65));
        wordFrequencies.add(new WordFrequency("Cincinnati", 65));
        wordFrequencies.add(new WordFrequency("Porto Alegre", 62));
        wordFrequencies.add(new WordFrequency("Seongnam-si", 60));
        wordFrequencies.add(new WordFrequency("Dearborn", 57));
        wordFrequencies.add(new WordFrequency("Portland", 56));
        wordFrequencies.add(new WordFrequency("Zhengzhou", 53));
        wordFrequencies.add(new WordFrequency("Lisbon", 53));
        wordFrequencies.add(new WordFrequency("Novosibirsk", 53));
        wordFrequencies.add(new WordFrequency("Mountain View", 53));
        wordFrequencies.add(new WordFrequency("Beijing", 52));
        wordFrequencies.add(new WordFrequency("Gothenburg", 52));
        wordFrequencies.add(new WordFrequency("Milan", 49));
        wordFrequencies.add(new WordFrequency("Porto", 49));
        wordFrequencies.add(new WordFrequency("Singapore", 49));
        wordFrequencies.add(new WordFrequency("Setagaya City", 48));
        wordFrequencies.add(new WordFrequency("Osaka", 47));
        wordFrequencies.add(new WordFrequency("Bucharest", 46));
        wordFrequencies.add(new WordFrequency("Bogota", 44));
        wordFrequencies.add(new WordFrequency("Dubai", 43));
        wordFrequencies.add(new WordFrequency("Lodz", 43));
        wordFrequencies.add(new WordFrequency("Phoenix", 43));
        wordFrequencies.add(new WordFrequency("Gdansk", 42));
        wordFrequencies.add(new WordFrequency("Kazan", 42));
        wordFrequencies.add(new WordFrequency("Santiago", 41));
        wordFrequencies.add(new WordFrequency("Shanghai", 40));
        wordFrequencies.add(new WordFrequency("Copenhagen", 40));
        wordFrequencies.add(new WordFrequency("Utrecht", 40));
        wordFrequencies.add(new WordFrequency("Hanoi", 40));
        wordFrequencies.add(new WordFrequency("Yokohama", 39));
        wordFrequencies.add(new WordFrequency("Cluj-Napoca", 39));
        wordFrequencies.add(new WordFrequency("Brno", 38));
        wordFrequencies.add(new WordFrequency("Dallas", 38));
        wordFrequencies.add(new WordFrequency("Brisbane", 36));
        wordFrequencies.add(new WordFrequency("Florianopolis", 36));
        wordFrequencies.add(new WordFrequency("Zagreb", 36));
        wordFrequencies.add(new WordFrequency("Ahmedabad", 36));
        wordFrequencies.add(new WordFrequency("Haifa", 36));
        wordFrequencies.add(new WordFrequency("Uberlandia", 35));
        wordFrequencies.add(new WordFrequency("Sunnyvale", 35));
        wordFrequencies.add(new WordFrequency("Calgary", 33));
        wordFrequencies.add(new WordFrequency("Brentford", 33));
        wordFrequencies.add(new WordFrequency("Vilnius", 33));
        wordFrequencies.add(new WordFrequency("Recife", 31));
        wordFrequencies.add(new WordFrequency("Rome", 31));
        wordFrequencies.add(new WordFrequency("Dnipro", 31));
        wordFrequencies.add(new WordFrequency("Lviv", 31));
        wordFrequencies.add(new WordFrequency("Brussels", 30));
        wordFrequencies.add(new WordFrequency("Shenzhen", 30));
        wordFrequencies.add(new WordFrequency("Leeds", 30));
        wordFrequencies.add(new WordFrequency("Columbus", 30));
        wordFrequencies.add(new WordFrequency("Vancouver", 29));
        wordFrequencies.add(new WordFrequency("Chisinau", 29));
        wordFrequencies.add(new WordFrequency("Cambridge", 29));
        wordFrequencies.add(new WordFrequency("Tallinn", 29));
        wordFrequencies.add(new WordFrequency("Ghent", 28));
        wordFrequencies.add(new WordFrequency("Sofia", 28));
        wordFrequencies.add(new WordFrequency("Mexico City", 28));
        wordFrequencies.add(new WordFrequency("San Diego", 28));
        wordFrequencies.add(new WordFrequency("Atlanta", 28));
        wordFrequencies.add(new WordFrequency("Riga", 28));
        wordFrequencies.add(new WordFrequency("Leinfelden-Echterdingen", 27));
        wordFrequencies.add(new WordFrequency("Rotterdam", 27));
        wordFrequencies.add(new WordFrequency("Auckland", 27));
        wordFrequencies.add(new WordFrequency("Ulyanovsk", 27));
        wordFrequencies.add(new WordFrequency("Reston", 27));
        wordFrequencies.add(new WordFrequency("Quebec City", 26));
        wordFrequencies.add(new WordFrequency("Lyon", 26));
        wordFrequencies.add(new WordFrequency("Cambridge", 26));
        wordFrequencies.add(new WordFrequency("Essen", 25));
        wordFrequencies.add(new WordFrequency("Manchester", 25));
        wordFrequencies.add(new WordFrequency("Nairobi", 25));
        wordFrequencies.add(new WordFrequency("Gliwice", 25));
        wordFrequencies.add(new WordFrequency("Cape Town", 25));
        wordFrequencies.add(new WordFrequency("Medellin", 24));
        wordFrequencies.add(new WordFrequency("Puteaux", 24));
        wordFrequencies.add(new WordFrequency("Gurgaon", 24));
        wordFrequencies.add(new WordFrequency("Pleasanton", 24));
        wordFrequencies.add(new WordFrequency("Boulder", 24));
        wordFrequencies.add(new WordFrequency("Curitiba", 23));
        wordFrequencies.add(new WordFrequency("Guangzhou", 23));
        wordFrequencies.add(new WordFrequency("Leipzig", 23));
        wordFrequencies.add(new WordFrequency("Nanterre", 23));
        wordFrequencies.add(new WordFrequency("Irvine", 23));
        wordFrequencies.add(new WordFrequency("Midvale", 23));
        wordFrequencies.add(new WordFrequency("Newcastle upon Tyne", 22));
        wordFrequencies.add(new WordFrequency("Bandung", 22));
        wordFrequencies.add(new WordFrequency("Santa Clara", 22));
        wordFrequencies.add(new WordFrequency("Cairo", 21));
        wordFrequencies.add(new WordFrequency("Bristol", 21));
        wordFrequencies.add(new WordFrequency("Bologna", 21));
        wordFrequencies.add(new WordFrequency("Voronezh", 21));
        wordFrequencies.add(new WordFrequency("Cherkasy", 21));
        wordFrequencies.add(new WordFrequency("Brooklyn Park", 21));
        wordFrequencies.add(new WordFrequency("Athens", 21));
        wordFrequencies.add(new WordFrequency("Ulm", 20));
        wordFrequencies.add(new WordFrequency("Dusseldorf", 20));
        wordFrequencies.add(new WordFrequency("Brighton", 20));
        wordFrequencies.add(new WordFrequency("Shinagawa City", 20));
        wordFrequencies.add(new WordFrequency("Glendale", 20));
        wordFrequencies.add(new WordFrequency("Zaandam", 20));
        wordFrequencies.add(new WordFrequency("Graz", 19));
        wordFrequencies.add(new WordFrequency("Issy-les-Moulineaux", 19));
        wordFrequencies.add(new WordFrequency("Kyoto", 19));
        wordFrequencies.add(new WordFrequency("Redwood City", 19));
        wordFrequencies.add(new WordFrequency("Kansas City", 19));
        wordFrequencies.add(new WordFrequency("Berkeley", 19));
        wordFrequencies.add(new WordFrequency("Tysons", 19));
        wordFrequencies.add(new WordFrequency("Kosice", 19));
        wordFrequencies.add(new WordFrequency("Bern", 18));
        wordFrequencies.add(new WordFrequency("Zaragoza", 18));
        wordFrequencies.add(new WordFrequency("Nantes", 18));
        wordFrequencies.add(new WordFrequency("York", 18));
        wordFrequencies.add(new WordFrequency("Indore", 18));
        wordFrequencies.add(new WordFrequency("Sapporo", 18));
        wordFrequencies.add(new WordFrequency("Makati", 18));
        wordFrequencies.add(new WordFrequency("Ankara", 18));
        wordFrequencies.add(new WordFrequency("Montevideo", 18));
        wordFrequencies.add(new WordFrequency("Oakland", 18));
        wordFrequencies.add(new WordFrequency("Detroit", 18));
        wordFrequencies.add(new WordFrequency("Cleveland", 18));
        wordFrequencies.add(new WordFrequency("Nashville", 18));
        wordFrequencies.add(new WordFrequency("Brasilia", 17));
        wordFrequencies.add(new WordFrequency("San Jose", 17));
        wordFrequencies.add(new WordFrequency("Ingolstadt", 17));
        wordFrequencies.add(new WordFrequency("Hanover", 17));
        wordFrequencies.add(new WordFrequency("Bordeaux", 17));
        wordFrequencies.add(new WordFrequency("Courbevoie", 17));
        wordFrequencies.add(new WordFrequency("New Delhi", 17));
        wordFrequencies.add(new WordFrequency("Arnhem", 17));
        wordFrequencies.add(new WordFrequency("Bialystok", 17));
        wordFrequencies.add(new WordFrequency("Katowice", 17));
        wordFrequencies.add(new WordFrequency("Palo Alto", 17));
        wordFrequencies.add(new WordFrequency("Pittsburgh", 17));
        wordFrequencies.add(new WordFrequency("Wolfsburg", 16));
        wordFrequencies.add(new WordFrequency("Reading", 16));
        wordFrequencies.add(new WordFrequency("Enschede", 16));
        wordFrequencies.add(new WordFrequency("Christchurch", 16));
        wordFrequencies.add(new WordFrequency("Nizhny Novgorod", 16));
        wordFrequencies.add(new WordFrequency("New Cairo City", 16));
        wordFrequencies.add(new WordFrequency("Blue Ash", 16));
        wordFrequencies.add(new WordFrequency("Fortaleza", 15));
        wordFrequencies.add(new WordFrequency("Araraquara", 15));
        wordFrequencies.add(new WordFrequency("Osasco", 15));
        wordFrequencies.add(new WordFrequency("Mississauga", 15));
        wordFrequencies.add(new WordFrequency("Cesson-Sevigne", 15));
        wordFrequencies.add(new WordFrequency("Lagos", 15));
        wordFrequencies.add(new WordFrequency("Hoofddorp", 15));
        wordFrequencies.add(new WordFrequency("The Hague", 15));
        wordFrequencies.add(new WordFrequency("Iasi", 15));
        wordFrequencies.add(new WordFrequency("Los Gatos", 15));
        wordFrequencies.add(new WordFrequency("Aracaju", 14));
        wordFrequencies.add(new WordFrequency("Carp", 14));
        wordFrequencies.add(new WordFrequency("Ottawa", 14));
        wordFrequencies.add(new WordFrequency("Basel", 14));
        wordFrequencies.add(new WordFrequency("Bracknell", 14));
        wordFrequencies.add(new WordFrequency("Koto City", 14));
        wordFrequencies.add(new WordFrequency("Guadalajara", 14));
        wordFrequencies.add(new WordFrequency("Kuala Lumpur", 14));
        wordFrequencies.add(new WordFrequency("Eindhoven", 14));
        wordFrequencies.add(new WordFrequency("Rzeszow", 14));
        wordFrequencies.add(new WordFrequency("Szczecin", 14));
        wordFrequencies.add(new WordFrequency("Solna", 14));
        wordFrequencies.add(new WordFrequency("Overland Park", 14));
        wordFrequencies.add(new WordFrequency("Ann Arbor", 14));
        wordFrequencies.add(new WordFrequency("Belgrade", 14));
        wordFrequencies.add(new WordFrequency("Richfield", 14));
        wordFrequencies.add(new WordFrequency("Cordoba", 13));
        wordFrequencies.add(new WordFrequency("Antwerp", 13));
        wordFrequencies.add(new WordFrequency("Geneva", 13));
        wordFrequencies.add(new WordFrequency("Kleinmachnow", 13));
        wordFrequencies.add(new WordFrequency("Ismaning", 13));
        wordFrequencies.add(new WordFrequency("Grenoble", 13));
        wordFrequencies.add(new WordFrequency("Edinburgh", 13));
        wordFrequencies.add(new WordFrequency("Fukuoka", 13));
        wordFrequencies.add(new WordFrequency("Malmo", 13));
        wordFrequencies.add(new WordFrequency("Odesa", 13));
        wordFrequencies.add(new WordFrequency("Baltimore", 13));
        wordFrequencies.add(new WordFrequency("Eden Prairie", 13));
        wordFrequencies.add(new WordFrequency("Philadelphia", 13));
        wordFrequencies.add(new WordFrequency("Brookfield", 13));
        wordFrequencies.add(new WordFrequency("Bergen Municipality", 13));
        wordFrequencies.add(new WordFrequency("Ljubljana", 13));
        wordFrequencies.add(new WordFrequency("Abu Dhabi", 12));
        wordFrequencies.add(new WordFrequency("Malaga", 12));
        wordFrequencies.add(new WordFrequency("Rennes", 12));
        wordFrequencies.add(new WordFrequency("Seclin", 12));
        wordFrequencies.add(new WordFrequency("Glasgow", 12));
        wordFrequencies.add(new WordFrequency("Surabaya", 12));
        wordFrequencies.add(new WordFrequency("Lahore", 12));
        wordFrequencies.add(new WordFrequency("Vinnytsia", 12));
        wordFrequencies.add(new WordFrequency("San Mateo", 12));
        wordFrequencies.add(new WordFrequency("Indianapolis", 12));
        wordFrequencies.add(new WordFrequency("Omaha", 12));
        wordFrequencies.add(new WordFrequency("Franklin", 12));
        wordFrequencies.add(new WordFrequency("Farmington Hills", 12));
        wordFrequencies.add(new WordFrequency("Almaty", 12));
        wordFrequencies.add(new WordFrequency("Delhi", 12));
        wordFrequencies.add(new WordFrequency("Adelaide", 11));
        wordFrequencies.add(new WordFrequency("Linz", 11));
        wordFrequencies.add(new WordFrequency("Joinville", 11));
        wordFrequencies.add(new WordFrequency("Ribeirao Preto", 11));
        wordFrequencies.add(new WordFrequency("Augsburg", 11));
        wordFrequencies.add(new WordFrequency("Brunswick", 11));
        wordFrequencies.add(new WordFrequency("Munster", 11));
        wordFrequencies.add(new WordFrequency("Palma", 11));
        wordFrequencies.add(new WordFrequency("Lannion", 11));
        wordFrequencies.add(new WordFrequency("Toulouse", 11));
        wordFrequencies.add(new WordFrequency("Lille", 11));
        wordFrequencies.add(new WordFrequency("Salford", 11));
        wordFrequencies.add(new WordFrequency("Belfast", 11));
        wordFrequencies.add(new WordFrequency("Guatemala City", 11));
        wordFrequencies.add(new WordFrequency("Szeged", 11));
        wordFrequencies.add(new WordFrequency("Noida", 11));
        wordFrequencies.add(new WordFrequency("Cork", 11));
        wordFrequencies.add(new WordFrequency("Timisoara", 11));
        wordFrequencies.add(new WordFrequency("Kemerovo", 11));
        wordFrequencies.add(new WordFrequency("Linkoping", 11));
        wordFrequencies.add(new WordFrequency("Lund", 11));
        wordFrequencies.add(new WordFrequency("Fremont", 11));
        wordFrequencies.add(new WordFrequency("Boise", 11));
        wordFrequencies.add(new WordFrequency("Bloomington", 11));
        wordFrequencies.add(new WordFrequency("Redmond", 11));
        wordFrequencies.add(new WordFrequency("Sandton", 11));
        wordFrequencies.add(new WordFrequency("Tartu", 11));
        wordFrequencies.add(new WordFrequency("Maribor", 11));
        wordFrequencies.add(new WordFrequency("Campo Grande", 10));
        wordFrequencies.add(new WordFrequency("Santo Andre", 10));
        wordFrequencies.add(new WordFrequency("Hangzhou", 10));
        wordFrequencies.add(new WordFrequency("Dortmund", 10));
        wordFrequencies.add(new WordFrequency("Alcobendas", 10));
        wordFrequencies.add(new WordFrequency("Tampere", 10));
        wordFrequencies.add(new WordFrequency("Strasbourg", 10));
        wordFrequencies.add(new WordFrequency("Kefar Sava", 10));
        wordFrequencies.add(new WordFrequency("Ota City", 10));
        wordFrequencies.add(new WordFrequency("Msida", 10));
        wordFrequencies.add(new WordFrequency("Deventer", 10));
        wordFrequencies.add(new WordFrequency("Krasnodar", 10));
        wordFrequencies.add(new WordFrequency("Yekaterinburg", 10));
        wordFrequencies.add(new WordFrequency("Bentonville", 10));
        wordFrequencies.add(new WordFrequency("Campbell", 10));
        wordFrequencies.add(new WordFrequency("Bristol", 10));
        wordFrequencies.add(new WordFrequency("Washington", 10));
        wordFrequencies.add(new WordFrequency("Glenview", 10));
        wordFrequencies.add(new WordFrequency("Framingham", 10));
        wordFrequencies.add(new WordFrequency("Morrisville", 10));
        wordFrequencies.add(new WordFrequency("Eugene", 10));
        wordFrequencies.add(new WordFrequency("Puchong", 10));
        wordFrequencies.add(new WordFrequency("Cestas", 10));
        wordFrequencies.add(new WordFrequency("Holladay", 10));
        wordFrequencies.add(new WordFrequency("Quito", 10));


        final Dimension dimension = new Dimension(1000, 350 + 38 / 2);
        final WordCloud wordCloud = new WordCloud(dimension, CollisionMode.PIXEL_PERFECT);
        wordCloud.setPadding(2);
        wordCloud.setBackgroundColor(Color.WHITE);
        wordCloud.setBackground(new PixelBoundryBackground("mockk.png"));
        wordCloud.setAngleGenerator(new AngleGenerator(0));
        wordCloud.setColorPalette(
                new ColorPalette(
                        new Color(0xfdb100),
                        new Color(0xfe7e00),
                        new Color(0xff6600),
                        new Color(0xF140C5),
                        new Color(0xff00ff),
                        new Color(0x5500ff),
                        new Color(0x0000ff),
                        new Color(0x00aa55),
                        new Color(0x00ff00)
                )
        );
        wordCloud.setFontScalar(new LinearFontScalar(10, 40));
        wordCloud.build(wordFrequencies);
        wordCloud.writeToFile("wordcloud.png");
    }
}
